server:
  port: 18086
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: 192.168.181.128:9200
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.181.128
    virtual-host: /zhuyuhao
    username: zhuyuhao
    password: yomikiss
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
  jackson:
    default-property-inclusion: non_null
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug