server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: pms-route
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: sms-route
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: ums-route
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: oms-route
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: search-route
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com #Host可以通过域名判断请求是否进入该路由
        - id: index-route1 # 首页的同步请求路由
          uri: lb://index-service
          predicates:
            - Host=www.gmall.com
          # - Path=/index/**  如果写在一个里面，他们的关系是and关系
        - id: index-route2 # 首页的异步请求路由
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: item-route1
          uri: lb://item-service
          predicates:
            - Path=/item/**
        - id: item-route2
          uri: lb://item-service
          predicates:
            - Host=item.gamll.com
    nacos:
      discovery:
        server-addr: localhost:8848