server:
  port: 18089
# nacos
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  #feign熔断功能
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: D:\project\6.9\rsa\rsa.pub
  priKeyPath: D:\project\6.9\rsa\rsa.pri
  secret: adsfasdf@{+}adsfjASKLDJF))(ASDIF&@#234
  expire: 240
  cookieName: GMALL-TOKEN
  unick: unick


